base_url = "https://rs4rse.github.io"
title = "Rust for RSE"
description = "A Research Software Engineer Rust community"

compile_sass = true
build_search_index = false
generate_feeds = true

[markdown]
highlight_code = true

[slugify]
paths_keep_dates = true

[extra]
feedback_url = "https://rs4rse.github.io/feedback" 
source_url = "https://github.com/rs4rse/rs4rse.github.io"
chat_url = "https://bit.ly/rs4rse-slack"

